# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaEAlfabeto.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EAlfabeto(object):
    def setupUi(self, EAlfabeto):
        EAlfabeto.setObjectName("EAlfabeto")
        EAlfabeto.resize(411, 165)
        self.centralwidget = QtWidgets.QWidget(EAlfabeto)
        self.centralwidget.setObjectName("centralwidget")
        self.bAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.bAceptar.setGeometry(QtCore.QRect(150, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bAceptar.setFont(font)
        self.bAceptar.setObjectName("bAceptar")
        self.Error = QtWidgets.QLabel(self.centralwidget)
        self.Error.setGeometry(QtCore.QRect(70, 20, 271, 61))
        self.Error.setObjectName("Error")
        EAlfabeto.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EAlfabeto)
        self.statusbar.setObjectName("statusbar")
        EAlfabeto.setStatusBar(self.statusbar)

        self.retranslateUi(EAlfabeto)
        QtCore.QMetaObject.connectSlotsByName(EAlfabeto)

    def retranslateUi(self, EAlfabeto):
        _translate = QtCore.QCoreApplication.translate
        EAlfabeto.setWindowTitle(_translate("EAlfabeto", "MainWindow"))
        self.bAceptar.setText(_translate("EAlfabeto", "Aceptar"))
        self.Error.setText(_translate("EAlfabeto", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Error en la transicion,</span></p><p align=\"center\"><span style=\" font-size:14pt;\">no coincide con el alfabeto</span></p></body></html>"))
